name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/n4v1ds0n/dungeoncrawler:latest .

      - name: Push Docker image
        run: docker push ghcr.io/n4v1ds0n/dungeoncrawler:latest