name: Run Docker Image from GitHub Packages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.PAT_TOKEN }} # noqa

      - name: Pull Docker image
        run: docker pull ghcr.io/n4v1ds0n/dungeoncrawler:latest

      - name: Run container in background
        run: docker run -d --rm --name dungeon -p 5000:5000 ghcr.io/n4v1ds0n/dungeoncrawler:latest

      - name: Wait for the server to start
        run: sleep 10

      - name: Test the server
        run: curl --fail http://localhost:5000 || (echo "App not responding!" && exit 1)

      - name: Show logs (optional)
        run: docker logs dungeon

      - name: Stop the container
        run: docker stop dungeon